### ISSUE TITLE
06/02 Code Review

### ISSUE THREAD

**Issue by hsiangfeng** [callumzhong/hex-team-post-backend#13]
## 主要審核分支 main

cc. @EmptyWu 

- Ｊㄍ是...國王的新組長？
![圖片](https://user-images.githubusercontent.com/19990752/171553970-33d61a51-488d-4174-86b6-822e5547f95c.png)
- README 可以多描述一下該專案以及如何還原專案、環境變數，助教一打開宛如通靈一般猜出環境變數。
![通靈學院](https://user-images.githubusercontent.com/19990752/171553984-23eaa640-19af-4f36-a73f-ecd2e6ebe898.jpg)
- swagger-output.json 可以不用加入到版本控制內，因為本身是編譯產生的。
- 不需要註解記得刪除。
- 縮排的定位點跟空格請統一，swagger.js 採用定位點作為縮排，建議改成空格，可詳見[[此篇](https://israynotarray.com/vscode/20210512/2779926364/)](https://israynotarray.com/vscode/20210512/2779926364/)開啟。
- package-lock.json 建議要上傳到版本控制內，可以透過[[這一篇](https://israynotarray.com/nodejs/20211027/1827968017/)](https://israynotarray.com/nodejs/20211027/1827968017/)認識一下。
- 可以試著加入 ESLint 加入統一風格。
- 沒有使用的功能記得刪除，如：app.js 的 13 行。
- 建議統一下 router `require` 寫法，一下子有 .js 一下子沒有 .js。
- 程式碼就是最好的註解，因此有些地方可以思考一下是否不用再寫註解了，如：app.js。
- 許多地方都可以轉為傳統函式縮寫，如：service/wallet.service.js。
- 可以試著使用解構語法解構。

```jsx
// 原始
let page=req.query.page;
let search=req.query.q;
let sort=req.query.sort;
let like=req.query.like;

// 解構

let { page, search, sort, like } = req.query;
```

- ES6 語法 `const` 跟 `let` 可以區分一下差異。
- service/post.service.js 的 created 建議改成以下

```jsx
async created (req) {		
		const {
			id,
			tags,
			type, 
			image, 
			contentType,
			likes, 
			comments
		} = req.body;
		const newPost = await Post.create({
			user,
			tags,
			type,
			image,
			contentType,
			content,
			likes,
			comments,
		  });
		  return newPost;
	},
```

不要一個一個 `req.body` 寫那麼辛苦。

- 函式命名請使用駝峰式大小寫，如：service/post.service.js 94 行。
- `followuser` ⇒ `followUser`。
- 不需要的 router 記得刪除。
- 前後端分離狀態下，是不太需要 public 資料夾的。
- 在使用 Model 時 Mongoose 會自己轉換成複數的，然後首字會自己變成小寫，因此通常會是單數且首字大寫，如：user.js 的 57 行。
- swagger 的文件產生註解可以整理一下。

## 需要注意的部分

- 程式碼中風格非常明顯不統一，建議多加注意一下。
- 部分地方沒有試著使用解構等 ES6 語法變成很累贅，建議團隊成為試著導入 Code Review。
- 程式碼中相當多多餘的空格、換行等請多加注意這個。

**Comment by caffbit** [comment]
* 組長是 Jordan_Tseng , notion 已更新
* READMD 我們找時間補上
* 關於 swagger 改用 express-jsdoc-swagger 套件不會產生 JSON , 排版好整理
* 使用 yarn 管理套件這點有上傳 yarn.lock 版本紀錄
* 對於 "風格不統一" , "過於累贅的物件未使用解構" , "命名規範" 這些我們在磨合一下

有問題不了解的是

* 請問如 service/wallet.service.js 說的改成傳統函式撰寫的意思是?
  1. 不要使用箭頭函式 ?
  2. 不要使用 aggregate ?

**Comment by hsiangfeng** [comment]
> * 組長是 Jordan_Tseng , notion 已更新
> 
>     * READMD 我們找時間補上
> 
>     * 關於 swagger 改用 express-jsdoc-swagger 套件不會產生 JSON , 排版好整理
> 
>     * 使用 yarn 管理套件這點有上傳 yarn.lock 版本紀錄
> 
>     * 對於 "風格不統一" , "過於累贅的物件未使用解構" , "命名規範" 這些我們在磨合一下
> 
> 
> 有問題不了解的是
> 
>     * 請問如 service/wallet.service.js 說的改成傳統函式撰寫的意思是?
>       
>       1. 不要使用箭頭函式 ?
>       2. 不要使用 aggregate ?

```js
async getCurrentWallet(userId) { ... }
```
